// Complete conversion-focused homepage.
import { BookingForm } from "./components/BookingForm";
import { CallToAction } from "./components/CallToAction";
import { siteConfig } from "./site-config";

export default function Home() {
  return (
    <>
      <section className="home-hero">
        <div className="container hero-grid">
          <div className="hero-copy"><p className="eyebrow">Same-day service available</p><h1>Reliable comfort.<br /><em>Right when you need it.</em></h1><p className="lead">Expert heating, cooling, and indoor air quality solutions—delivered by local technicians who treat your home like their own.</p><div className="hero-actions"><a className="button" href="/contact">Book service <span>→</span></a><a className="text-link" href="/services">Explore services <span>↗</span></a></div><div className="hero-rating"><div className="avatar-stack"><span>JM</span><span>RK</span><span>AL</span></div><div><strong>4.9 <span>★★★★★</span></strong><small>Trusted by 2,000+ local homeowners</small></div></div></div>
          <div className="hero-art" aria-label="Home comfort illustration"><div className="art-sun" /><div className="home-shape" /><div className="thermostat"><small>HOME COMFORT</small><strong>72°</strong><span>Perfectly comfortable</span><i /></div><div className="emergency"><b>24/7</b><span>Emergency<br />support</span></div><span className="airflow one">≈</span><span className="airflow two">≈</span></div>
        </div>
        <div className="container trust-bar"><span>✓ Licensed &amp; insured</span><span>✓ Upfront pricing</span><span>✓ Satisfaction guaranteed</span><span>✓ Locally owned</span></div>
      </section>

      <section className="section services-preview"><div className="container"><div className="section-heading split"><div><p className="eyebrow">Whole-home comfort</p><h2>Expert help for every season.</h2></div><p>Whether your system stopped working or you’re planning a smarter upgrade, our team makes the next step clear.</p></div><div className="service-grid">{siteConfig.services.map((service, index) => <article className={`service-card${index === 0 ? " featured" : ""}`} key={service.title}><span className="service-icon">{service.icon}</span><div><h3>{service.title}</h3><p>{service.short}</p></div><a href="/services" aria-label={`Learn about ${service.title}`}>Learn more <span>→</span></a></article>)}</div><div className="section-center"><a className="outline-button" href="/services">View all services</a></div></div></section>

      <section className="section why-us"><div className="container why-grid"><div className="why-visual"><div className="technician-shape"><span>AC</span></div><div className="experience-badge"><strong>{new Date().getFullYear() - siteConfig.business.yearStarted}+</strong><span>years serving<br />local homes</span></div></div><div className="why-copy"><p className="eyebrow">Comfort without the runaround</p><h2>Clear answers. Careful work. No surprises.</h2><p>Great HVAC service is about more than equipment. It’s about arriving prepared, listening closely, and giving you honest options that make sense for your home.</p><div className="benefit-list"><div><span>01</span><h3>Respectful service</h3><p>Background-checked technicians, shoe covers, and tidy work areas.</p></div><div><span>02</span><h3>Options, not pressure</h3><p>Clear recommendations with the pros, costs, and tradeoffs explained.</p></div><div><span>03</span><h3>Work built to last</h3><p>Quality parts, careful commissioning, and a satisfaction promise.</p></div></div><a className="text-link" href="/about">Meet AeroComfort <span>→</span></a></div></div></section>

      <section className="section process-section"><div className="container"><div className="section-heading centered"><p className="eyebrow">Simple from start to finish</p><h2>Comfort in three easy steps.</h2></div><div className="process-grid"><article><span>1</span><h3>Tell us what’s happening</h3><p>Call or request service online. We’ll ask a few quick questions and find a convenient appointment.</p></article><article><span>2</span><h3>Get clear recommendations</h3><p>Your technician diagnoses the issue and walks you through practical options before work begins.</p></article><article><span>3</span><h3>Relax in a comfortable home</h3><p>We complete approved work, test performance, clean up, and review everything with you.</p></article></div></div></section>

      <section className="section reviews-section"><div className="container"><div className="section-heading split"><div><p className="eyebrow">Neighbors recommend us</p><h2>Service that feels different.</h2></div><div className="review-score"><strong>4.9</strong><span>★★★★★<small>2,000+ verified customers</small></span></div></div><div className="review-grid">{siteConfig.reviews.map((review) => <figure key={review.name}><div className="quote-mark">“</div><blockquote>{review.quote}</blockquote><figcaption><span>{review.name.split(" ").map((n) => n[0]).join("")}</span><div><strong>{review.name}</strong><small>{review.detail}</small></div></figcaption></figure>)}</div></div></section>

      <section className="section membership"><div className="container membership-grid"><div><p className="eyebrow light">AeroCare membership</p><h2>Fewer surprises. More peace of mind.</h2><p>Protect your system with seasonal maintenance, priority scheduling, and member-only savings.</p><a className="button light-button" href="/services">Explore maintenance <span>→</span></a></div><ul><li><span>✓</span> Two seasonal tune-ups each year</li><li><span>✓</span> Priority appointment scheduling</li><li><span>✓</span> 15% savings on most repairs</li><li><span>✓</span> No after-hours diagnostic premium</li><li><span>✓</span> Automatic maintenance reminders</li></ul></div></section>

      <section className="section faq-section"><div className="container faq-grid"><div><p className="eyebrow">Helpful answers</p><h2>Questions homeowners ask us.</h2><p>Still deciding what you need? Our team can help you make sense of symptoms, options, and timing.</p><a className="text-link" href="/resources">Visit our resource center <span>→</span></a></div><div className="faq-list">{siteConfig.faqs.slice(0,4).map((faq, index) => <details key={faq.q} open={index === 0}><summary>{faq.q}<span>+</span></summary><p>{faq.a}</p></details>)}</div></div></section>

      <section className="section booking-section"><div className="container booking-grid"><div><p className="eyebrow">Request an appointment</p><h2>Let’s get your comfort back.</h2><p>Send a quick request and our team will contact you to confirm availability. For urgent issues, call us directly.</p><a className="booking-phone" href={`tel:${siteConfig.contact.phoneHref}`}><small>Call now</small>{siteConfig.contact.phoneDisplay}</a><div className="mini-hours"><span>{siteConfig.hours[0]}</span><span>{siteConfig.contact.emergencyLabel}</span></div></div><BookingForm compact /></div></section>
      <CallToAction />
    </>
  );
}
// End complete homepage.
